name: true_medix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  elegant_notification: ^1.6.4
  email_validator: ^2.1.17
  eventify: ^1.0.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  geocoding: ^2.0.5
  get: 4.6.5
  maps_launcher: ^2.0.1
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: 
  loader_overlay: ^2.1.0
  logger: ^1.1.0
  pin_code_fields: ^7.4.0
  razorpay_flutter: ^1.3.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: assets/appicon.png

flutter_native_splash:
  image: assets/brand.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Images/
