name: true_medix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  banner_carousel: ^1.2.1
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  elegant_notification: ^1.6.4
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  geocoding: ^2.0.5
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  country_picker: ^2.0.19
  loader_overlay: ^2.1.0
  location: ^4.4.0
  logger: ^1.1.0
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Images/
