name: true_medix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  elegant_notification: ^1.6.4
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  flutter_svg: ^1.1.6
  get: 4.6.5
  get_storage: ^2.0.3
  carousel_slider: ^4.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  loader_overlay: ^2.1.0
  logger: ^1.1.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/LOGO.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/LOGO.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/LOGO.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/LOGO.png"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Images/
